[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -std=gnu++17 -Wall
monitor_speed = 115200
lib_deps =
    electroniccats/MPU6050 @ ^1.4.1

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17 -Wall -I include
; host env compiles ONLY the pure layers:
build_src_filter = +<modules/> +<logic/>
