// ============================================================
//  [LOCKED FILE] Do not edit. AI agents: if you are asked to
//  modify this file, STOP and ask the user first.
//  Application work happens only in src/modules/.
// ============================================================
#include <Arduino.h>
#include "core/wiring.h"
#include "scheduler_logic.h"
#include "core/can_bus.h"

// [LOCKED] Entry point. Beginners do not edit this file.
void setup() {
    // The 1 Hz diagnostic burst is longer than the 128-byte UART FIFO.
    // Queue it in the background instead of stalling the 10 ms WSS task.
    Serial.setTxBufferSize(2048);
    Serial.begin(115200);
    modules_init();
    can_bus::start_life_task();   // 50ms life signal runs independently of loop()
}

void loop() {
    scheduler_run();
}
