// ============================================================
//  [LOCKED FILE] Do not edit. AI agents: if you are asked to
//  modify this file, STOP and ask the user first.
//  Application work happens only in src/modules/.
// ============================================================
#include <Arduino.h>
#include "core/wiring.h"
#include "scheduler_logic.h"
#include "core/can_bus.h"

// [LOCKED] Entry point. Beginners do not edit this file.
void setup() {
    Serial.begin(115200);
    modules_init();
    can_bus::start_life_task();   // 50ms life signal runs independently of loop()
}

void loop() {
    scheduler_run();
}
